os:
  - linux
  - osx
language: go
go:
  - 1.7.3
  - tip
addons:
  apt:
    packages:
      - oracle-java8-set-default
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install java; fi
env:
  - GAUGE_ROOT="/tmp/gauge"
before_install:
  - go get github.com/tools/godep
install:
  - godep restore
script:
  - go run build/make.go
  - go test ./...
  - echo "gauge_repository_url = https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/" >> skel/gauge.properties
  - go run build/make.go --install --prefix=$GAUGE_ROOT
  - git clone --depth=1 https://github.com/getgauge/gauge-tests
  - cd gauge-tests
  - $GAUGE_ROOT/bin/gauge --install-all
  - java -version
  - ./starttests.sh java