os:
  - linux
  - osx
language: go
go:
  - 1.7.3
  - tip
before_install:
 - go get github.com/tools/godep
install:
 - godep restore
script:
  - go run build/make.go
  - go test ./...
  - echo "gauge_repository_url = https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/" >> skel/gauge.properties
  - go run build/make.go -install
  - git clone --depth=1 https://github.com/getgauge/gauge-tests
  - cd gauge-tests
  - gauge --install-all
  - ./starttests.sh java